=== Konstantin060290/HTML/XML/ITMO.XML.L2T1_lessons.dtd
<!ELEMENT lessons (lesson)>
<!ELEMENT lesson (title, teacher, duration, time_period, grade)>
<!ATTLIST lesson description CDATA "Заполни">
<!ELEMENT title (#PCDATA)>
<!ELEMENT teacher (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT time_period (#PCDATA)>
<!ELEMENT grade (#PCDATA)>

=== Konstantin060290/HTML/XML/ITMO.XML.L2T1_lessons.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE lessons SYSTEM "D:\Coding\ITMO\5_XML\Labs\ITMO.XML.L2T1_lessons.dtd">
<lessons>
  <lesson description="Предмет №1">
    <title>Технологии программирования</title>
    <teacher>Осипов Н.А.</teacher>
    <duration>50 часов</duration>
    <time_period>29.09.20...16.10.20</time_period>
    <grade>Зачет</grade>
  </lesson>
  <lesson description="Предмет №2">
    <title>Программирование на C#</title>
    <teacher>Осипов Н.А.</teacher>
    <duration>50 часов</duration>
    <time_period>19.10.20...06.11.20</time_period>
    <grade>Зачет</grade>
  </lesson>
  <lesson description="Предмет №3">
    <title>Введение в базы данных</title>
    <teacher>Осетрова И.С.</teacher>
    <duration>30 часов</duration>
    <time_period>09.11.20...20.11.20</time_period>
    <grade>Зачет</grade>
  </lesson>
</lessons>
